### ISSUE TITLE
Will it support jsonschma validation against AWS glue

### ISSUE THREAD

**Issue by Optimusprime-2021** [awslabs/aws-glue-schema-registry#100]
What is value Converter class name for json format converter in Kafka connect the example is given with Avro converter

**Comment by Optimusprime-2021** [comment]
Looks it supports only Avro . We have Json schema, want to validate agains AWS glue registry then write in s3 through Kafka connect.

**Comment by Optimusprime-2021** [comment]
key.converter=com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter
    value.converter=com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter
    
Can you tell me what is the value converter class name for json example mentioned only Avro . Will it support json?

**Comment by blacktooth** [comment]
Yes, we support JSON as well.  You can configure your converters to use JSON [converters](https://github.com/awslabs/aws-glue-schema-registry/blob/master/jsonschema-kafkaconnect-converter/src/main/java/com/amazonaws/services/schemaregistry/kafkaconnect/jsonschema/JsonSchemaConverter.java)

**Comment by blacktooth** [comment]
Does above suggestion work for you?

**Comment by blacktooth** [comment]
Assuming above guidance helped. Please feel free to re-open otherwise.
