### ISSUE TITLE
How to connect to AWS Glue Schema registry using C# .Net code ?

### ISSUE THREAD

**Issue by neerajk22** [awslabs/aws-glue-schema-registry#116]
Looking for some C# sample code for connectivity to AWS Glue schema registry. 
If any sample code using AWS .NET SDK will be helpful.

**Comment by vanessapinto257** [comment]
Hello,

Thanks for your interest in Glue Schema Registry. Support for .NET is on the roadmap. If you are looking to call Schema Registry APIs, you can use the [Glue .NET SDK](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Glue/TGlueClient.html). Serializers / Deserializers in .NET are not officially supported. If you are interested in building one, you can refer to the [wire format](https://github.com/awslabs/aws-glue-schema-registry/blob/master/serializer-deserializer/src/main/java/com/amazonaws/services/schemaregistry/deserializers/GlueSchemaRegistryDeserializerDataParser.java). It should be similar to this.

**Comment by blacktooth** [comment]
We are tracking C# support [here](https://github.com/awslabs/aws-glue-schema-registry/issues/43). Resolving as duplicate.
