### ISSUE TITLE
Support for testing Schema Registry locally

### ISSUE THREAD

**Issue by ed0906** [awslabs/aws-glue-schema-registry#13]
Hi,
We are looking to integrate our Kafka Streams app with Glue Schema Registry. 
One obstacle for us is how we stub out Glue Schema Registry in our integration tests which use TopologyTestDriver. 

Would you mind adding some guidance docs on how best to approach this?
The Confluent Schema Registry library offers this class which makes it easy, something similar for AWS Glue would be much appreciated https://github.com/confluentinc/schema-registry/blob/master/client/src/main/java/io/confluent/kafka/schemaregistry/testutil/MockSchemaRegistry.java

Many thanks

**Comment by blacktooth** [comment]
Hi,

Thanks for your interest in Glue Schema Registry! 

We will consider this feature in our upcoming releases. 

1. Can you explain more about how will you enable the integration mode? Do you prefer passing a configuration option like `testingMode = true` and we return mocked responses? 
2. Do you have a workaround to unblock yourself till we build this feature?

**Comment by MeiSign** [comment]
Hello @blacktooth,

is there any roadmap or rough timeline when this feature might be available?

We are actively looking for a workaround to mock the registry but don’t want to invest too much effort if there is a real solution on the way.

**Comment by blacktooth** [comment]
Sorry for delay on this. This item is on our roadmap. We are targeting to build it before Q3 this year.

**Comment by FabianF92** [comment]
@blacktooth Do you know if is planned to bring GLUE registry in localstack? For our IT Tests we would prefer this solution.

**Comment by mohitpali** [comment]
@FabianF92 That's the idea. For now we have introduced a module called integration-tests that can be used with a provided Kafka docker image. Schema Registry, however, is still remote.

**Comment by ShakeelHussain** [comment]
Hello everyone 
We are stuck here too, we are using aws msk and glue schema registry. In the dev environment for  MSK, we are using Kafka but in the case of the glue schema registry, we are stuck. 
Any update on when we are rolling out this feature?

**Comment by YangSan0622** [comment]
Hello everyone,
Sorry about the late update, we have added the GSR support in moto last year in this PR: https://github.com/getmoto/moto/pull/5351
You should be able to use moto for testing GSR locally now.

**Comment by poojaprama** [comment]
> Hello everyone We are stuck here too, we are using aws msk and glue schema registry. In the dev environment for MSK, we are using Kafka but in the case of the glue schema registry, we are stuck. Any update on when we are rolling out this feature?

please let me know if you get the solution

**Comment by jvdadda** [comment]
@YangSan0622 Why are you talking about a Python mock library for a Java issue ? (and you permit yourself to mark the issue as completed ?)

**Comment by krickert** [comment]
So I'm looking into using this as a testcontainer to do the tests.  Let me know if anyone has already tried this.  This architecture makes it a royal pain to do a mock server.

I'd really recommend allowing a simple mock tag in the configuration.  It slows down development to use glue directly and/or just using confluent in one environment and hoping it works right in AWS.
