### ISSUE TITLE
Question: Docker image of Glue registry

### ISSUE THREAD

**Issue by wlaw868** [awslabs/aws-glue-schema-registry#162]
Hello, we are looking for a docker image for Glue registry so that we can test locally before sending to dev or prod cluster. Is there a plan for it on the roadmap?

**Comment by hhkkxxx133** [comment]
Hi,

Thanks for your interest! We do have this task on our roadmap but we don't have an ETA at this moment. Please track this under the issue #13. I will close this issue due to duplication.
