### ISSUE TITLE
Use a specific schema and version in Kafka Connect converter without auto-registering?

### ISSUE THREAD

**Issue by lukewestby** [awslabs/aws-glue-schema-registry#163]
Hi folks,

I'm working on using Glue Schema Registry to provide an Avro schema for a source connector. What I would like to do is simply specify the registry name, schema name, and schema version and serialize incoming records using that specific schema. This is as opposed to having the connector convert Connect schemas into Avro schemas. I want to write the schema myself and then provide it directly to the connector. If incoming data is incompatible with the specified Avro schema in some way I would want the Connect task to fail rather than attempting to auto-register a new version of the Avro schema derived from the Connect schema.

Is this setup possible?

Thank you!

**Comment by y-lahrichi** [comment]
> Hello,
> 
> Glue Schema Registry library does not support serializing the data by specific schema in the source connector. However, you can disable auto-registration by setting `properties.put(AWSSchemaRegistryConstants.SCHEMA_AUTO_REGISTRATION_SETTING, false)` (it is `false` by default, so not specifying also works). [Ref](https://github.com/awslabs/aws-glue-schema-registry#using-auto-registration)

Is serializing by specific schema on the roadmap? I have a use case where I want to enforce a schema on my source record messages.
