### ISSUE TITLE
Readme - Broken Link for "Providing Schema Name" implementation example

### ISSUE THREAD

**Issue by WhiskyTangoFawks** [awslabs/aws-glue-schema-registry#195]
As per title, the link for the example implementation in the readme for Providing Schema Name is broken

**Comment by YangSan0622** [comment]
Hello, thank you so much for your finding! We will fix that when we make our next release. Meanwhile, we strongly encourage everyone in the community to raise a PR to fix issues they find. In this case, a PR is welcomed to fix this documentation issue.
