### ISSUE TITLE
AWS Glue schema registry with python

### ISSUE THREAD

**Issue by HarshPathakhp** [awslabs/aws-glue-schema-registry#20]
Hi All,
Since glue schema registry is restricted to java for now, what are my options if I want to use it with python kafka producer and consumers? 

My initial assumption was that glue SR and confluent SR may have the same design and importantly the same interface, so I looked more into the confluent Kafka client for python, which has a schema registry client [here](https://docs.confluent.io/platform/current/clients/confluent-kafka-python/#schemaregistry-client). This client requires a `url` property. This is not the case with the java SerDe libraries [link](https://docs.aws.amazon.com/glue/latest/dg/schema-registry-gs.html#schema-registry-gs-serde), which take in properties such as region name, registry name, etc. The glue schema registry does not have any URL associated with it (I can't find it neither on the console nor in glue SR documentation). I looked into the AWS SDK implementation for making the API call to schema registry, but it seems complex to be able to reconstruct the URL from the input properties, and with no guarantees it will work with kafka schema registry client. Even the AWS CLI uses simple parameters like region name, ARN of glue registry, with no mention of any url.

On a side note, [this link](https://docs.aws.amazon.com/glue/latest/dg/schema-registry-integrations.html#schema-registry-integrations-migration)(under property KafkaAvroDeserializerConfig.SCHEMA_REGISTRY_URL_CONFIG)  asks for a third party SR url for migration purposes. This leads me to believe that a URL can indeed be constructed for glue SR as well, which will imply confluent kafka probably can be used on it. 
 
What do you think is the best way to approach to integrate glue SR and use with python clients? If using kafka SR client is not possible, I can consider implementing my own SerDe on python using the registry APIs (boto3). I will appreciate your thoughts on this.

Thanks

**Comment by blacktooth** [comment]
Glue Schema Registry (GSR) is a fully managed Schema Registry with infrastructure hosted by AWS. GSR doesn't require any urls to be passed as it's centrally hosted by AWS. The Java SerDe library interacts with Glue Schema Registry service by making calls to [Glue service endpoints](https://docs.aws.amazon.com/general/latest/gr/glue.html). The Glue Schema Registry service supports APIs to author, retrieve and manage schema versions. You can find the list of APIs [here](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-schema-registry-api.html#aws-glue-api-schema-registry-api-actions). 

The property `KafkaAvroDeserializerConfig.SCHEMA_REGISTRY_URL_CONFIG` can be used if you are migrating from a third-party schema registry. It only accepts URL to a non-AWS managed Schema Registry if you want to move to AWS GSR. 

Python support is on our roadmap. We don't have a timeline for now. If you are looking to implement a version of the SerDe in Python, you can invoke the GSR APIs using boto3 client. You can consider embedding the schema version Ids into the messages by modifying the initial bytes of the message. Here's the [code](https://github.com/awslabs/aws-glue-schema-registry/blob/master/avro-serializer-deserializer/src/main/java/com/amazonaws/services/schemaregistry/serializers/SerializationDataEncoder.java#L45) for how the Java SerDe library does it. The decoding process is inverse of it. You can find it [here](https://github.com/awslabs/aws-glue-schema-registry/blob/master/avro-serializer-deserializer/src/main/java/com/amazonaws/services/schemaregistry/deserializers/AWSDeserializerDataParser.java#L126). 

We welcome contributions if you are willing to develop and open source it! :)

**Comment by HarshPathakhp** [comment]
Thanks @blacktooth. Your answer addresses my question well and answers my queries. I will close this now.

**Comment by hiramf** [comment]
@blacktooth 
> Python support is definitely on our roadmap. We don't have a timeline as of now.

Are there any updates to the timeline for this?

**Comment by solebox** [comment]
Any updates on the timeline?

**Comment by clintmod** [comment]
There is this lib: https://pypi.org/project/aws-glue-schema-registry/

**Comment by krgannon** [comment]
Any updates on a python client? The opensource one mentioned above has a rust dependency I'd like to avoid

**Comment by alberttwong** [comment]
https://pypi.org/project/aws-glue-schema-registry/ doesn't seems to work with MSK with AWS Glue schema registry.  At least I couldn't get it to work.  https://github.com/DisasterAWARE/aws-glue-schema-registry-python/issues/26

**Comment by alberttwong** [comment]
asking kafka-python to support AWS Glue Schema Registry https://github.com/wbarnha/kafka-python-ng/issues/182
