### ISSUE TITLE
AWSSchemaRegistryClient can't be reused for different schemas

### ISSUE THREAD

**Issue by FabianF92** [awslabs/aws-glue-schema-registry#23]
Hi,

just a minor thing, that is not blocking us, but might be useful to implement:

`AWSSchemaRegistryClient` takes the compatibility setting and description from private field `glueSchemaRegistryConfiguration`:
```
private CreateSchemaRequest getCreateSchemaRequestObject(String schemaName, String dataFormat, String schemaDefinition) {
        return CreateSchemaRequest
                .builder()
                .dataFormat(DataFormat.valueOf(dataFormat))
                .description(glueSchemaRegistryConfiguration.getDescription())
                .registryId(RegistryId.builder().registryName(glueSchemaRegistryConfiguration.getRegistryName()).build())
                .schemaName(schemaName)
                .schemaDefinition(schemaDefinition)
                .compatibility(glueSchemaRegistryConfiguration.getCompatibilitySetting())
                .tags(glueSchemaRegistryConfiguration.getTags())
                .build();
    }
```
This means that we can't use the same client instance for different schemas, cause every schema has other description or eventually also other compatibility level. 
Might make sense that description and compatibility are also method parameters?
All in all, I am wondering if it makes sense to have `compatibility` and `description` as part of `GlueSchemaRegistryConfiguration` because they really depend on the schema. All other fields are more "global" settings that have same value for every schema. What do you think?

Just as background: We do not register our schemas via the serializer, but have an own pipeline that loops through all of our schemas and registers them with a client instance. With the current implementation, I need own instance per schema with new config to pass individual description.

**Comment by mohitpali** [comment]
Thanks for reaching out to us. If you are just using the client, would it make sense if we provide you with an overridden method that takes `compatibility` and `description` as parameters that you can use ?

We can also provide the `description` and `compatibility` as a part of schema naming strategy.

Let us know what do you think.

**Comment by mohitpali** [comment]
As an alternate, you could also use Glue SDK to create glue client and that way you can work without serializer/deserializer library. If you are using auto registration, then you may have to wrap some logic in your client.

**Comment by FabianF92** [comment]
> Thanks for reaching out to us. If you are just using the client, would it make sense if we provide you with an overridden method that takes `compatibility` and `description` as parameters that you can use ?
> 
> We can also provide the `description` and `compatibility` as a part of schema naming strategy.
> 
> Let us know what do you think.

Yes, that is the same way we did it now in our temporary custom solution.
Would make sense to pass description and compatibility as parameter to `getORRegisterSchemaVersionId`.

**Comment by mohitpali** [comment]
Great to hear that you have a custom solution working. Does that unblock you or would you like to have this incorporated from Schema Registry ?

**Comment by blacktooth** [comment]
Assuming this is fixed. Please feel free to re-open if you are still facing this.
