### ISSUE TITLE
AWS Glue Schema Registry support for .NET CORE

### ISSUE THREAD

**Issue by cr-urra** [awslabs/aws-glue-schema-registry#233]
Hello,

I am currently developing consumption and production services with KAFKA agents with .NET and AWS MSK, to do data validation I must use AWS Glue Schema Registry, however from what I read in the minimum requirements and examples, there are only examples in JAVA, do you currently support .NET?

Thank you very much.

**Comment by YangSan0622** [comment]
Hello, 
AWS Glue Schema Registry Client Library only supports Java at this point. However, we are currently working on providing .NET support and it will be released in near future.
