### ISSUE TITLE
Vulnerablilities Wire Schema 3.7.1

### ISSUE THREAD

**Issue by franoisD** [awslabs/aws-glue-schema-registry#235]
![image](https://user-images.githubusercontent.com/88726257/201984600-ad8b9e03-74a8-4ac1-bf43-764085fa3c84.png)

Related pull request:
https://github.com/awslabs/aws-glue-schema-registry/pull/230

**Comment by allkliu** [comment]
These vulnerabilities don't affect us as we don't create temporary files on disk, according to @blacktooth
