### ISSUE TITLE
SecondaryDeserializer should not be a singleton

### ISSUE THREAD

**Issue by FabianF92** [awslabs/aws-glue-schema-registry#25]
Hi,

we are migrating our deserializers to GLUE using the fallback option with `SecondaryDeserializer`.
We have both Avro `SpecificDatumReader` and `GenericDatumReader` in our project so we need to have different types of `SecondaryDeserializer`. 
However, the `SecondaryDeserializer` is a singleton and we can't have two instances of it.
It would be better if the we can have one `SecondaryDeserializer` instance per `AWSKafkaAvroDeserializer`.

**Comment by mohitpali** [comment]
I can update the changelog on your behalf. Thanks for the PR.
