### ISSUE TITLE
AWS Glue Schema Registry + MSK Serverless + MSK Connect

### ISSUE THREAD

**Issue by berlinodeveloper** [awslabs/aws-glue-schema-registry#258]
Is there an option to use MSK Serverless and MSK Connect with Glue Schema Registry?
I think there is no option to add a plugin to the CLASSPATH of the Serverless cluster.
Thanks to anyone who provides a solution.

**Comment by blacktooth** [comment]
Here's a blog post on how to use MSK Connect with Glue Schema Registry, https://aws.amazon.com/blogs/big-data/build-an-end-to-end-change-data-capture-with-amazon-msk-connect-and-aws-glue-schema-registry/

>  I think there is no option to add a plugin to the CLASSPATH of the Serverless cluster.

GSR works on the Kafka client side and doesn't require any changes to the cluster. Are you facing issues using GSR with serverless clusters?

**Comment by berlinodeveloper** [comment]
Thanks for sharing the blog post.
We are using MSK Serverless and Connect with Confluent JDBC Source Connector and BigQuery Sink Connector.
However the above plugins don't have GSR jars natively. We merge them in a new zip plugin to make Connect works properly.

The last problem we have is that the auto creation of the topics is disabled by default in MSK Serverless Cluster broker configuration.
The only example to do that in the MSK serverless documentation is by using Kakfa client scripts with secured IAM authentication.
I know there is not related to the issue in the title but I appreciate any help.
