### ISSUE TITLE
Can't I use a java class created via gradle-avro-plugin as a specific record type for the consumer?

### ISSUE THREAD

**Issue by 21kyu** [awslabs/aws-glue-schema-registry#295]
We are using `bitnami/schema-registry` locally to produce and consume records in the form of SPECIFIC_RECORD.

In this process, we are using the class generated through https://github.com/davidmc24/gradle-avro-plugin as the type, and when we try to use Glue Schema Registry in the k8s cluster environment as it is, the following error occurs.

`org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing key/value for partition xxx-result-0 at offset 0. If needed, please seek past the record to continue consumption`

I did check the [documentation](https://github.com/awslabs/aws-glue-schema-registry#dealing-with-specific-record-java-pojo-for-json) on handling specific records utilizing JAVA POJO.

What I want to check: I would like to ask if it is not possible to use objects created via gradle-avro-plugin when using glue schema registry.

**Comment by YangSan0622** [comment]
Can you share a minimal setup for us to reproduce the issue so we can look into it?

**Comment by 21kyu** [comment]
Oh, sorry.
It was a mismatch in the schema I had declared. I matched the schema and retested, and it works fine.

I'll close this issue now.
Thank you.
