### ISSUE TITLE
ProtobufSchemaConverter fails in v1.1.18

### ISSUE THREAD

**Issue by ifurman** [awslabs/aws-glue-schema-registry#328]
I'm trying to use ProtobufSchemaConverter with MSK Connect and Confluent S3 Sink connector. The converter fails with the following error:

java.io.FileNotFoundException: /proc/353/fd/4 (No such file or directory)

Note, that the same connector works fine with v1.1.13
Here's the relevant log:
`
[Worker-07d4ebf79aed77144] [2024-02-03 00:32:34,951] ERROR [msk-s3backup-connector-v3|task-0] Error encountered in task msk-s3backup-connector-v3-0. Executing stage 'VALUE_CONVERTER' with class 'com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.ProtobufSchemaConverter'. (org.apache.kafka.connect.runtime.errors.LogReporter:66)
[Worker-07d4ebf79aed77144] com.amazonaws.services.schemaregistry.exception.AWSSchemaRegistryException: Exception occurred while de-serializing Protobuf message
"[Worker-07d4ebf79aed77144] 	at com.amazonaws.services.schemaregistry.deserializers.protobuf.ProtobufDeserializer.deserialize(ProtobufDeserializer.java:77)"
"[Worker-07d4ebf79aed77144] 	at com.amazonaws.services.schemaregistry.deserializers.GlueSchemaRegistryDeserializationFacade.deserialize(GlueSchemaRegistryDeserializationFacade.java:172)"
"[Worker-07d4ebf79aed77144] 	at com.amazonaws.services.schemaregistry.deserializers.GlueSchemaRegistryKafkaDeserializer.deserialize(GlueSchemaRegistryKafkaDeserializer.java:116)"
"[Worker-07d4ebf79aed77144] 	at com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.ProtobufSchemaConverter.toConnectData(ProtobufSchemaConverter.java:114)"
"[Worker-07d4ebf79aed77144] 	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)"
"[Worker-07d4ebf79aed77144] 	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertValue(WorkerSinkTask.java:545)"
"[Worker-07d4ebf79aed77144] 	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$1(WorkerSinkTask.java:501)"
"[Worker-07d4ebf79aed77144] 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)"
"[Worker-07d4ebf79aed77144] 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)"
"[Worker-07d4ebf79aed77144] 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:132)"
"[Worker-07d4ebf79aed77144] 	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:501)"
"[Worker-07d4ebf79aed77144] 	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:478)"
"[Worker-07d4ebf79aed77144] 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:328)"
"[Worker-07d4ebf79aed77144] 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)"
"[Worker-07d4ebf79aed77144] 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)"
"[Worker-07d4ebf79aed77144] 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:189)"
"[Worker-07d4ebf79aed77144] 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:238)"
"[Worker-07d4ebf79aed77144] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)"
"[Worker-07d4ebf79aed77144] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)"
"[Worker-07d4ebf79aed77144] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)"
"[Worker-07d4ebf79aed77144] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)"
"[Worker-07d4ebf79aed77144] 	at java.base/java.lang.Thread.run(Thread.java:829)"
[Worker-07d4ebf79aed77144] Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.io.FileNotFoundException: /proc/353/fd/4 (No such file or directory)
"[Worker-07d4ebf79aed77144] 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2055)"
"[Worker-07d4ebf79aed77144] 	at com.google.common.cache.LocalCache.get(LocalCache.java:3966)"
"[Worker-07d4ebf79aed77144] 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989)"
"[Worker-07d4ebf79aed77144] 	at com.amazonaws.services.schemaregistry.deserializers.protobuf.ProtobufDeserializer.deserialize(ProtobufDeserializer.java:73)"
"[Worker-07d4ebf79aed77144] 	... 22 more"
[Worker-07d4ebf79aed77144] Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /proc/353/fd/4 (No such file or directory)
"[Worker-07d4ebf79aed77144] 	at com.amazonaws.services.schemaregistry.utils.apicurio.FileDescriptorUtils.toFileDescriptorProto(FileDescriptorUtils.java:160)"
"[Worker-07d4ebf79aed77144] 	at com.amazonaws.services.schemaregistry.utils.apicurio.FileDescriptorUtils.protoFileToFileDescriptor(FileDescriptorUtils.java:151)"
"[Worker-07d4ebf79aed77144] 	at com.amazonaws.services.schemaregistry.utils.apicurio.FileDescriptorUtils.protoFileToFileDescriptor(FileDescriptorUtils.java:142)"
"[Worker-07d4ebf79aed77144] 	at com.amazonaws.services.schemaregistry.deserializers.protobuf.ProtobufSchemaParser.parse(ProtobufSchemaParser.java:15)"
"[Worker-07d4ebf79aed77144] 	at com.amazonaws.services.schemaregistry.deserializers.protobuf.ProtobufDeserializer$ProtobufSchemaParserCache.load(ProtobufDeserializer.java:124)"
"[Worker-07d4ebf79aed77144] 	at com.amazonaws.services.schemaregistry.deserializers.protobuf.ProtobufDeserializer$ProtobufSchemaParserCache.load(ProtobufDeserializer.java:120)"
"[Worker-07d4ebf79aed77144] 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)"
"[Worker-07d4ebf79aed77144] 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)"
"[Worker-07d4ebf79aed77144] 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)"
"[Worker-07d4ebf79aed77144] 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)"
"[Worker-07d4ebf79aed77144] 	... 26 more"
[Worker-07d4ebf79aed77144] Caused by: java.io.FileNotFoundException: /proc/353/fd/4 (No such file or directory)
"[Worker-07d4ebf79aed77144] 	at java.base/java.io.RandomAccessFile.open0(Native Method)"
"[Worker-07d4ebf79aed77144] 	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)"
"[Worker-07d4ebf79aed77144] 	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)"
"[Worker-07d4ebf79aed77144] 	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)"
"[Worker-07d4ebf79aed77144] 	at okio.JvmSystemFileSystem.openReadOnly(JvmSystemFileSystem.kt:83)"
"[Worker-07d4ebf79aed77144] 	at okio.internal.ZipFilesKt.openZip(ZipFiles.kt:67)"
"[Worker-07d4ebf79aed77144] 	at okio.internal.ResourceFileSystem$Companion.toJarRoot(ResourceFileSystem.kt:201)"
"[Worker-07d4ebf79aed77144] 	at okio.internal.ResourceFileSystem$Companion.toClasspathRoots(ResourceFileSystem.kt:184)"
"[Worker-07d4ebf79aed77144] 	at okio.internal.ResourceFileSystem$roots$2.invoke(ResourceFileSystem.kt:47)"
"[Worker-07d4ebf79aed77144] 	at okio.internal.ResourceFileSystem$roots$2.invoke(ResourceFileSystem.kt:47)"
"[Worker-07d4ebf79aed77144] 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)"
"[Worker-07d4ebf79aed77144] 	at okio.internal.ResourceFileSystem.getRoots(ResourceFileSystem.kt:47)"
"[Worker-07d4ebf79aed77144] 	at okio.internal.ResourceFileSystem.<init>(ResourceFileSystem.kt:51)"
"[Worker-07d4ebf79aed77144] 	at okio.Okio.asResourceFileSystem(Unknown Source)"
"[Worker-07d4ebf79aed77144] 	at com.squareup.wire.schema.CoreLoader$resourceFileSystem$2.invoke(CoreLoader.kt:46)"
"[Worker-07d4ebf79aed77144] 	at com.squareup.wire.schema.CoreLoader$resourceFileSystem$2.invoke(CoreLoader.kt:45)"
"[Worker-07d4ebf79aed77144] 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)"
"[Worker-07d4ebf79aed77144] 	at com.squareup.wire.schema.CoreLoader.getResourceFileSystem(CoreLoader.kt:45)"
"[Worker-07d4ebf79aed77144] 	at com.squareup.wire.schema.CoreLoader.load(CoreLoader.kt:51)"
"[Worker-07d4ebf79aed77144] 	at com.squareup.wire.schema.SchemaLoader.load(SchemaLoader.kt:140)"
"[Worker-07d4ebf79aed77144] 	at com.squareup.wire.schema.Linker.getFileLinker$wire_schema(Linker.kt:74)"
"[Worker-07d4ebf79aed77144] 	at com.squareup.wire.schema.Linker.link(Linker.kt:87)"
"[Worker-07d4ebf79aed77144] 	at com.squareup.wire.schema.SchemaLoader.loadSchema(SchemaLoader.kt:95)"
"[Worker-07d4ebf79aed77144] 	at com.amazonaws.services.schemaregistry.utils.apicurio.ProtobufSchemaLoader.loadSchema(ProtobufSchemaLoader.java:171)"
"[Worker-07d4ebf79aed77144] 	at com.amazonaws.services.schemaregistry.utils.apicurio.FileDescriptorUtils.toFileDescriptorProto(FileDescriptorUtils.java:158)"
"[Worker-07d4ebf79aed77144] 	... 35 more"
`
Here's the schema:

`
syntax = "proto3";

package com.my.kafka;

message NewS3Asset {
  string Bucket = 1;
  string Asset = 2;
  int64 InsertDate = 3;
  optional string OptionalDescriptionPROTO = 4;
  optional string TestMSKConnector = 5;
}
`

Relevant connector config:
`
value.converter.region=us-east-1, \
value.converter.endpoint=https://glue.us-east-1.amazonaws.com, \
value.converter.schemas.enable=true, \
value.converter.registry.name=test-glue-registry, \
value.converter.schemaName=NewS3AssetValueSchema, \
value.converter.schemaAutoRegistrationEnabled=true, \
value.converter.dataFormat=protobuf, \
value.converter.protobufMessageType=DYNAMIC_MESSAGE, \
value.converter=com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.ProtobufSchemaConverter " \

`

**Comment by gabistoenescu** [comment]
How was this problem solved?
We're having exactly the same issue when the not-configurable ProtobufDeserializer fails to find a schema that presumably it understood how to cache.

**Comment by metropolis-ameer** [comment]
We downgraded to `1.1.15` at that time.  We will test out `1.1.20` soon.

**Comment by deepak-matta** [comment]
how this is resolved ?
I'm also getting same exception
