### ISSUE TITLE
Extend customization of schema naming strategy

### ISSUE THREAD

**Issue by jagpat** [awslabs/aws-glue-schema-registry#33]
Hello,

We would like to publish schema from kafka connect to glue schema registry. We would like to name the created schemas in glue registry as \<topicname\>-key and \<topicname\>-value. 
So we implemented AWSSchemaNamingStrategy interface using CustomerSchemaNamingStrategy as an example. However the overridden method "public String getSchemaName(String transportName, Object data)" do not provide information on whether the schema is for key or for value so we cannot append "-key" or "-value" to the topicname to derive the schema name. Since the "AWSKafkaAvroSerializer::configure()" method already has isKey as the parameter, would you be able to extend the AWSSchemaNamingStrategy to include a method  getSchemaName(String transportName, Object data, boolean isKey)" ? Or is there any other way we would be able to determine whether the schema name is for the key or value ? Thanks!

**Comment by mohitpali** [comment]
Thanks for reaching out, we will look into this.
