### ISSUE TITLE
Is protobuf support planned in the future?

### ISSUE THREAD

**Issue by Balhau** [awslabs/aws-glue-schema-registry#34]
Hi all.

After digging a bit on the codebase I didn't find serializers/deserializers for protocol buffers. I would like to know if there is plan to support this format or if there is no plans for it in the foreseeable future.

Thanks guys.

**Comment by blacktooth** [comment]
Hello,

We definitely have plans to support Protocol buffers but don't have an ETA as of now. Is this blocker for you to onboard to Glue Schema Registry?

Thanks

**Comment by Balhau** [comment]
Hello thanks for the reply.
We are currently evaluating the possibility to use protocol buffers as the serialization format for data in kafka topics. For that we would also know the solutions help with schema evolution. If the result of the ongoing evaluation turns to elect protocol buffers as the standard serialization format the choice of schema registry solution will derive from that choice.

Thanks again @blacktooth.

**Comment by anuragk-sportsbet** [comment]
At our organisation we are quite keen on this one too. Any ETA on this?

**Comment by mohitpali** [comment]
We do have plans to support protobuf but unfortunately we don't have an ETA as of now.

**Comment by blacktooth** [comment]
The development for this is in progress on separate branch.

**Comment by emmaroberts-nbs** [comment]
@blacktooth  please can you give us an update on the progress on protobuf functionality?

**Comment by blacktooth** [comment]
It is still under development. We will update once we have an ETA.

**Comment by einarjohnson** [comment]
Any ETA on this yet?

**Comment by mohitpali** [comment]
We don't have an ETA yet. We are developing it actively at the moment.

**Comment by HaroonSaid** [comment]
Do we expect an announcement for probuf support in upcoming reinvent?

**Comment by omeraha** [comment]
Joining the question - is there an ETA for protobuf support?

**Comment by kriss9** [comment]
Protobuf. Protobuf. Protobuf. This is currently the argument fueling a complete shift away from MSK for us...

**Comment by ankitharry1992** [comment]
Hello all,
We are actively under development for adding protobuf support to Glue Schema Registry with a target to launch in Q1 2022. In the meantime, we are ready with a beta version for this feature and would love for you to try it out and share early feedback with us! If you are interested in trying this feature out in beta, please get in touch with your AWS account team or reach out to me so that we can grant you early access to the feature.

Thanks.

**Comment by blacktooth** [comment]
Protobuf support is GA now! https://aws.amazon.com/about-aws/whats-new/2022/02/aws-glue-schema-registry-protocol-buffers/

Please try it out and let us know your feedback.

Thanks for your patience and support!
