### ISSUE TITLE
schema-registry-serde: everit dependency not available on maven central

### ISSUE THREAD

**Issue by daMupfel** [awslabs/aws-glue-schema-registry#53]
Hi,

I am trying to use the glue schema registry client provided by this github repository.

When loading the newest version of schema-registry-serde it can't find the everit dependency since newer versions do not seem to be pushed to it.

Is this supposed to work with maven central only?

Thanks in advance :)

**Comment by mohitpali** [comment]
Everit is distributed through jitpack and that could be why you are seeing this.

Could you please share the steps you are using here ?

**Comment by daMupfel** [comment]
Thanks for the reply.

Sorry, I wasn't particular clear in my question :).

I am already using the schema-registry-serde client. So far maven central was enough in order to get all dependencies.

Now with the update to 1.1.0 (which is available on maven central) the everit version is not found because it is only available on jitpack.

I would like to avoid adding another registry if not absolutely needed (like jitpack).

So my question was: Should schema-registry-serde work when only using maven central as a registry? Or is jitpack absolutly required (I did not find any documentation about this, so this is a bit confusing).

**Comment by mohitpali** [comment]
Everit GitHub documentation suggests -
"Note: from version 1.6.0, the library is primarily distributed through JitPack. Previous versions are also available through maven central."

You could find their documentation at -

https://github.com/everit-org/json-schema

**Comment by daMupfel** [comment]
That is nice and all, but I am not using everit directly. I only use it because I require the schema-registry-serde client.

I was expecting to not need any special setup when using it (imho this should be documented here, how should people know that an additional maven repo needs to be configured?)

**Comment by dude0001** [comment]
This also seems to be causing building the repo from a fresh clone to fail.

**Comment by mohitpali** [comment]
Fix will be available with 1.1.1 release

**Comment by daMupfel** [comment]
Thank you very much @mohitpali 🙇
