### ISSUE TITLE
Need to be able to specify a GSR

### ISSUE THREAD

**Issue by dude0001** [awslabs/aws-glue-schema-registry#56]
By default, schemas are getting created in default-registry. Is there a way to specify a different registry in GSR?

**Comment by mohitpali** [comment]
Have you tried setting the property 
```
properties.put(AWSSchemaRegistryConstants.REGISTRY_NAME, "MyRegistry");
```

**Comment by dude0001** [comment]
I am trying to use this from Kafka Connect. Where would I configure it there? Generally, you put the URL of the server in the worker or connector properties e.g. value.converter.schema.registry.url=http://localhost:8081. There doesn't seem to be a URL endpoint for GSR so I cannot use that. I have tried value.converter.schema.registry.registry_name=my-registry, but they still go to default-registry.

**Comment by mohitpali** [comment]
GSR does not have registry url notion. Library calls AWS SDK to connect to GSR. So just specifying these should work :
```
    value.converter=com.amazonaws.services.schemaregistry.kafkaconnect.AWSKafkaAvroConverter
    value.converter.region=ca-central-1
    value.converter.schemaAutoRegistrationEnabled=true
    value.converter.registry.name=myRegistry
    
```

**Comment by dude0001** [comment]
That is embarrassing, I should have been able to figure that out. I created #58 to help give the next user a nudge in the right direction. Thank you for the quick reply @mohitpali  and for getting me unblocked!

**Comment by mohitpali** [comment]
Happy to hear that you are unblocked. Thanks for creating the Pull Request.
