### ISSUE TITLE
Too much logging for AWSKafkaAvroSerializer (part two)

### ISSUE THREAD

**Issue by snemarch** [awslabs/aws-glue-schema-registry#63]
Hi, we're getting a "Schema Version Id is null. Trying to register the schema" log for every message serialized with the AWSKafkaAvroSerializer.

It seems that this was changed from info to debug in #9 , but changed back to info as part of #49 (commit a7017fb7a418f30d6302d3822e3464388228a72c). Re-changing the log level to debug would remove the spam, but I'm contemplating if there could be some underlying issues?

I haven't fully grokked the code, but in [AWSKafkaAvroSerializer#serialize](https://github.com/awslabs/aws-glue-schema-registry/blob/c9b9215fa5b976f27e251c0d38d18ae956c62f78/serializer-deserializer/src/main/java/com/amazonaws/services/schemaregistry/serializers/avro/AWSKafkaAvroSerializer.java#L102-L117) the null-check is against the final `schemaVersionId`... is there any feasible way to get this configured/initialized to be non-null?

My hunch is that either there's a bit of an architectural issue, or there's some configuration issue we've totally missed – it doesn't seem right that the lookup fails for each and every message. Fortunately the caching in `GlueSchemaRegistrySerializationFacade` seems to be working, though! 😅

**Comment by blacktooth** [comment]
Hi,

Is the code able to register the schema version successfully? Do you see any exceptions? Does the schema version show. up in the Glue Schema Registry console?

**Comment by blacktooth** [comment]
Re-directing the discussion to #64

**Comment by blacktooth** [comment]
Thanks for reporting this! Looks like the code got reverted in this file. We will investigate and fix it.

**Comment by snemarch** [comment]
> Thanks for reporting this! Looks like the code got reverted in this file. We will investigate and fix it.

Note that I think there's some underlying issue (possibly with our setup, we might very well have missed some configuration!), which will be masked out by re-changing the log level from info to debug.

Some more context, in case it helps: we're running a CDC pipeline: Postgres -> Debezium -> Kafka -> ElasticSearch, orchestrated with Kafka Connect. We're using AWS MSK and Glue Registry, while Connect is running in our own Kubernetes cluster.
