### ISSUE TITLE
Support for using temporary credentials

### ISSUE THREAD

**Issue by andyyaldoo** [awslabs/aws-glue-schema-registry#75]
Hi,

We have a use case where devs are developing locally using an IAM user in account A. But, the glue registry is in account B. We want to be able to get temporary credentials and then use this library to read / update the avro registry. Looking through the examples and the docs, there seems to be no documentation regarding that.

Is there a way to be able to pass AWS temporary credentials before interacting with AWS API a la https://docs.aws.amazon.com/AmazonS3/latest/userguide/AuthUsingTempSessionToken.html? Or is there an alternative here?

**Comment by blacktooth** [comment]
Hi,

You can use IAM assume role feature to temporarily request credentials for a role in different account. Steps to make this work,

1. Create a role like `SchemaRegistryAccess` in account B (where Schema Registry is created).
2. Ensure `SchemaRegistryAccess` role has policy `AWSGlueSchemaRegistryReadonlyAccess` (or `AWSGlueSchemaRegistryFullAccess`).
3. Add Account A and IAM user to trusted entities for this role.
4. Follow [this example](https://docs.aws.amazon.com/code-samples/latest/catalog/javav2-sts-src-main-java-com-example-sts-AssumeRole.java.html) for requesting credentials using assume-role and access the schema registry APIs in Account B.

Thanks for feedback on the documentation. We will enhance it!

**Comment by blacktooth** [comment]
@andyyaldoo Did above guidance help?

**Comment by andyyaldoo** [comment]
Hi @blacktooth, thank you for your reply. What do I do with the token? Do I just set it to env var? or do I pass it to the config? like:
```
properties.put(AWSSchemaRegistryConstants.ROLE_ARN, "<role_arn>");
```

I am aware of how to do assume role. What I'm not sure with is how we use the creds in the kafka client. As for other S3 services, there is an option to pass the `Credential` object to the client.

**Comment by blacktooth** [comment]
Do you use ec2s to access the schema registry? If so, you can configure cross-account access in your instance profile as described [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html) (See section "Allowing an instance profile role to switch to a role in another account")

We don't currently specifying role / credentials in the config. Let us know if above solution works, we will consider if this config needs to be provided for convenience.

**Comment by andyyaldoo** [comment]
>Do you use ec2s to access the schema registry?
Cross-account is only needed for local development

**Comment by blacktooth** [comment]
Yes, it uses the [DefaultCredentialProvider](https://github.com/awslabs/aws-glue-schema-registry/blob/master/serializer-deserializer/src/main/java/com/amazonaws/services/schemaregistry/serializers/GlueSchemaRegistryKafkaSerializer.java#L51) which can get the credentials from env variables, java system properties or ec2 instance profiles as described [here](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html). Do any of these work for your use-case?

**Comment by andyyaldoo** [comment]
@blacktooth we'll try the above and let you know. Thanks

**Comment by andyyaldoo** [comment]
> Do you use ec2s to access the schema registry? If so, you can configure cross-account access in your instance profile as described [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html) (See section "Allowing an instance profile role to switch to a role in another account")

Sorry, I missed this part of your reply. We don't use EC2 in local development, therefore we have to manually assume role before using the client. So, I'm afraid the link you provided wouldn't work for our case

**Comment by blacktooth** [comment]
>therefore we have to manually assume role before using the client

Is it possible to set the env variables or Java properties? That should also work.

**Comment by blacktooth** [comment]
Is this still an issue? Please feel free to reopen.
