### ISSUE TITLE
Field is unused

### ISSUE THREAD

**Issue by jherico** [awslabs/aws-glue-schema-registry#80]
https://github.com/awslabs/aws-glue-schema-registry/blob/a534d343ffac5727c482bbfb40a32e6b336f48c9/avro-kafkaconnect-converter/src/main/java/com/amazonaws/services/schemaregistry/kafkaconnect/AWSKafkaAvroConverter.java#L42

**Comment by hhkkxxx133** [comment]
Hello,

Thanks for reporting this to us! We will test and remove if not used. 

Thanks!

**Comment by mohitpali** [comment]
Constructor passes the configs to AbstractConfig that parses configurations from properties file.

**Comment by jherico** [comment]
@mohitpali I don't follow.  Even if the `AWSKafkaAvroConverterConfig` ctor has a side effect which is important, why is an instance of the class being stored in `AWSKafkaAvroConverter`?  If you removed the member and changed the code from `awsKafkaAvroConverterConfig = new AWSKafkaAvroConverterConfig(configs);` to `new AWSKafkaAvroConverterConfig(configs);` it would be functionally identical.  

The member variable is 
* private
* assigned but never read

That's a code smell and any decent Java linter will issue a warning about it.
