### ISSUE TITLE
Deserialise records that were serialised in another account

### ISSUE THREAD

**Issue by kokachev** [awslabs/aws-glue-schema-registry#81]
Is it possible to deserialise data that were serialised in another account (given that proper IAM permissions are in place)?
Serialiser creates and stores schema UUID with every message. Is this UUID unique globally or only within account?

One use case would be if data are replicated using MirrorMaker as blobs between two MSK clusters located in separate accounts.

Cheers,
Alex.

**Comment by hhkkxxx133** [comment]
Hello,

Thanks for reaching out to us! Schema version UUID is globally unique and you can access the schema in a different account using IAM assume role to grant the second account access to first account's schema registry. 

More instructions can be found #75 

Let me know if you have more questions.
