### ISSUE TITLE
Kafka 2.5.0 vulnerability - please update to 2.8.1 or newer

### ISSUE THREAD

**Issue by marcosscriven** [awslabs/aws-glue-schema-registry#82]
We have a security scanner that scans all direct and transitive dependencies of our software.

Kafka 2.5.0 came up with this https://sca.analysiscenter.veracode.com/vulnerability-database/security/timing-attack/java/sid-32216

> Apache Kafka is vulnerable to timing attack. The library validates password or key using `Arrays.equals`, allowing an attacker to leak credentials via brute force attacks.

Our top-level dependency is:

```
    <groupId>com.amazonaws</groupId>
    <artifactId>amazon-kinesis-producer</artifactId>
    <version>0.14.8</version>
```

Please could you update to `2.8.1` as it suggests? We also would then need the new release to be bumped in `amazon-kinesis-producer`.

**Comment by hhkkxxx133** [comment]
Hello,

Thanks for reaching out to us. We have upgraded the Kafka version to 2.8.1 in our library. We will publish a new release and work with `amazon-kinesis-producer` for a new release as well.

**Comment by blacktooth** [comment]
This was released. Thanks
