### ISSUE TITLE
SerDe class for Apache Avro with Kafka Streams

### ISSUE THREAD

**Issue by thaalesalves** [awslabs/aws-glue-schema-registry#87]
Hello! We're using MSK to stream messages here in the project, but I can't seem to find the SerDe class mentioned in the documentation. I have a simple producer app that uses the Client API to produce messages, and that one uses the regular Kafka libraries. The simple serializer and deserializer classes for use with the Client APIs are there and seem to be work properly, but the class `AWSKafkaAvroSerDe` mentioned specifically for the Kafka Streams API is proving hard to find. 

When I type `AWSKafkaAvro` and make the IDE autocomplete the entry, only `AWSKafkaAvroSerializer` and `AWSKafkaAvroDeserializer` are shown... `AWSKafkaAvroSerDe` isn't there.

Is there a specific lib for that class or am I doing something wrong here?

Doc I'm referring to [here](https://docs.aws.amazon.com/glue/latest/dg/schema-registry-integrations.html). The class mentioned can be found under the "Kafka Streams Application Example Code" section.

**Comment by blacktooth** [comment]
I hope above guidance helped. Please feel free to re-open otherwise.
