### ISSUE TITLE
Provide ability to specify the specific implementation of AwsCredentialsProvider

### ISSUE THREAD

**Issue by rampaldheeraj** [awslabs/aws-glue-schema-registry#94]
We are using Kubernetes for running our application and the IAM role of these applications are OIDS federated. The AwsCredentialsProvider that we use is WebTokenCredentialsProvider and the token is mounted inside the docker container. Now I know that in the `GlueSchemaRegistryKafkaSerializer` we use the `DefaultCredentialsProvider` and the behaviour is documented [here](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html). This is not working in our case, as the `DefaultCredentialsProvider` is not getting to the token. Instead it's just picking up some other credentials (from the host) and those credentials don't have permissions to access to the GlueSchemaRegistry. I got around this issue by extending the `GlueSchemaRegistryKafkaSerializer`  as
```public class CustomSerializer extends GlueSchemaRegistryKafkaSerializer {
    public CustomSerializer() {
        super(WebIdentityTokenFileCredentialsProvider.create(), null, null);
    }
}

```

And it works. I am not sure if there's a better way to do it. But it will be really good to have the ability to specify the credential provider to the serializer. Just like other aws service client libraries allow us to do.  Example 

```
AmazonSQSClientBuilder.standard()
                .withRegion(properties.getSigningRegion())
                .withCredentials(awsCredentialsProvider)
                .build();
```

**Comment by vanessapinto257** [comment]
Hi,

Thanks for reaching out! 
We do provide the ability to specify implementation of `AwsCredentialsProvider` as seen [here](https://github.com/awslabs/aws-glue-schema-registry/blob/6da694620e0e50205fb07da42103f6551a662a02/serializer-deserializer/src/main/java/com/amazonaws/services/schemaregistry/serializers/GlueSchemaRegistryKafkaSerializer.java#L49-L52) and [here](https://github.com/awslabs/aws-glue-schema-registry/blob/6da694620e0e50205fb07da42103f6551a662a02/serializer-deserializer/src/main/java/com/amazonaws/services/schemaregistry/serializers/GlueSchemaRegistryKafkaSerializer.java#L60-L69) for `GlueSchemaRegistryKafkaSerializer`.

Let me know if you have more questions.

**Comment by rampaldheeraj** [comment]
Thanks for getting back @vanessapinto257 . Yes, I saw that and I utilise this constructor as shown above in the code snippet. The thing is that the the producer configuration only takes the class name of the Serialiser and not the object.

`        producerProperties.put(
                ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG,
                GlueSchemaRegistryKafkaSerializer.class.getName());`
And the kafka Library uses the default constructor to create the serialiser.

```
    /**
     * Constructor used by Kafka producer when passing as the property.
     */
    public GlueSchemaRegistryKafkaSerializer() {
        this(DefaultCredentialsProvider.builder()
                     .build(), null, null);
    }
```

This constructor when invoked call another constructor which initialises the `AwsCredentialsProvider ` to `DefaultCredentialsProvider `.

```
    public GlueSchemaRegistryKafkaSerializer(AwsCredentialsProvider credentialProvider,
                                             UUID schemaVersionId,
                                             Map<String, ?> configs) {
        this.credentialProvider = (credentialProvider == null) ? DefaultCredentialsProvider.builder()
                .build() : credentialProvider;
        this.schemaVersionId = schemaVersionId;
        if (configs != null) {
            configure(configs, false);
        }
    }
```

I am looking for a way to specify the `AwsCredentialsProvider ` without having to override the `GlueSchemaRegistryKafkaSerializer` as I did . The code snippet is there on my question. 

Regards
Dheeraj Rampal

**Comment by blacktooth** [comment]
You can alternatively initialize your producer with serializers as show in the [Kafka documentation](https://kafka.apache.org/23/javadoc/index.html?org/apache/kafka/clients/producer/KafkaProducer.html), 

```
Properties props = new Properties();
props.put("bootstrap.servers", "localhost:9092");
props.put("transactional.id", "my-transactional-id");

Producer<String, String> producer = new KafkaProducer<>(props, new StringSerializer(), new StringSerializer());
```

**Comment by rampaldheeraj** [comment]
Thanks for getting back. This will definitely work. However I am using spring-kafka which provides ```kafka-template```, which can be initialised by providing an instance of ```ProducerFactory```.  At this moment I am occupied with some other assignment. I will try to find some time and do something similar to what you suggested with the ```ProducerFactory```. I will get back to you.

**Comment by blacktooth** [comment]
Thank you! Please feel free to re-open if you run into issues trying it.
